### PR TITLE
:ssh rename buffer

### PR DESCRIPTION
**Pull request by neeasade**
fixes https://github.com/riscy/shx-for-emacs/issues/11

### CODE REVIEW

**Comment by neeasade** [comment]
There are a few things I do want with this -- I'm using shx in combination with shell-pop[1] for convienent shells and bindings. The two issues I have right now:

- The window closes because we destroy the buffer, it would be nice to not disturb the layout
- If I'm editing a tramp buffer and I shell pop into a tramp session, it attempts to switch dirs by just sending 'cd /ssh: ...' and vanilla shell cd does not understand tramp syntax.

That last is more of an issue with shell-pop integration for me to figure out, just noting my limitations right now

[1] https://github.com/kyagi/shell-pop-el

config for reference: https://github.com/neeasade/emacs.d/blob/master/lisp/trees/shell.el#L39

**Comment by riscy** [comment]
I hacked around with this idea today -- what do you think of the behavior of something like this:
```elisp
(defun shx-cmd-ssh (host)
  "Open a shell on HOST using tramp.
\nThis way you benefit from the remote host's completions, and
commands like :pwd and :edit will work correctly.
\nExample:\n
  :ssh username@hostname:port"
  (if (equal host "")
      (shx-insert 'error "ssh <host>\n")
    (shx-insert "Connecting to " 'font-lock-doc-face host 'default "\n")
    (let ((host (replace-regexp-in-string ":" "#" host)))
      (setq-local default-directory (if (eq tramp-syntax 'default)
                                        (concat "/ssh:" host ":~")
                                      (concat "/" host ":~")))
      (kill-process)
      (shell (buffer-name shx-buffer)))))
```
We also have to add a check to line 219 along the lines of `(when (process-live-p process) (comint-send-string process "\n")))))` since we're swapping the process midstream.

**Comment by neeasade** [comment]
That works very well, thank you

**Comment by riscy** [comment]
Awesome - I'll merge this PR in as a basis for the change this weekend.  I think there are a few more tweaks that would help (handling a disconnect for instance) that I'll put in the next shx release.

**Pull request merged**
